#!/bin/bash

MAXNAMELENGTH=45


sacct --starttime `date +"%Y-%m-%d" --date='-1 month'` --format=JobID,JobName%${MAXNAMELENGTH},QOS,Elapsed,Time,NCPUS%3,NNodes%3,NodeList,Priority,End%22,State -s PD,R -X $@
